#!/usr/bin/env node
/**
 * Inlines src/content/blog/*.md into a generated TS module.
 *
 * The site runs on Cloudflare Workers, which has no filesystem at request
 * time. Reading the markdown with fs works during `next build` but returns
 * nothing in production, so every markdown-backed post 404s and the blog
 * index silently falls back to its hardcoded list. Bundling the posts as a
 * module keeps markdown as the authoring format while making the content
 * available to the Worker.
 *
 * Runs as part of `npm run build`. The output is committed so typecheck and
 * dev work on a fresh clone.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const POSTS_DIR = path.join(root, "src", "content", "blog");
const OUT_FILE = path.join(root, "src", "lib", "posts.generated.ts");

const entries = (await readdir(POSTS_DIR)).filter((f) => /\.mdx?$/i.test(f)).sort();

const posts = await Promise.all(
  entries.map(async (file) => ({
    slug: file.replace(/\.mdx?$/i, ""),
    raw: await readFile(path.join(POSTS_DIR, file), "utf8"),
  })),
);

const body = `// Generated by scripts/generate-posts.mjs. Do not edit by hand.
// Edit the markdown in src/content/blog/ and run \`node scripts/generate-posts.mjs\`.

export type RawPost = { slug: string; raw: string };

export const RAW_POSTS: RawPost[] = ${JSON.stringify(posts, null, 2)};
`;

await writeFile(OUT_FILE, body, "utf8");
console.log(`generate-posts: wrote ${posts.length} posts to ${path.relative(root, OUT_FILE)}`);
